"""Declaración de las 25 tablas del ZIP mensual de SICOP.

GENERADO por scripts/generar_tablas.py a partir de los CSV reales: los tipos
salen de los datos observados, no de suposiciones. Al cambiar el origen,
regenerar y revisar el diff (tests/test_tablas_spec.py valida contra el ZIP).

Criterios fijos:
  - Cédulas e identificadores son texto: llevan ceros a la izquierda.
  - Los nombres de institución, proveedor y procedimiento NO se guardan en los
    hechos; se derivan por join a las dimensiones. Sobre la tabla de
    invitaciones eso elimina ~52 % del volumen.
"""

from __future__ import annotations

from app.etl.tipos import Columna, Enriquecimiento, TablaSpec, validar_specs

TABLAS: tuple[TablaSpec, ...] = (
    TablaSpec(
        archivo="AdjudicacionesFirme.csv",
        tabla="adjudicaciones_firme",
        clave=('nro_acto',),
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NRO_ACTO", "nro_acto", "bigint"),
        Columna("FECHA_ADJ_FIRME", "fecha_adj_firme", "date"),
        Columna("PERMITE_RECURSOS", "permite_recursos", "boolean"),
        Columna("DESIERTO", "desierto", "boolean"),
        Columna("FECHA_REV", "fecha_rev", "timestamp"),
        ),
        indices=(('nro_sicop',),),
    ),
    TablaSpec(
        archivo="Contratos.csv",
        tabla="contratos",
        clave=('nro_contrato', 'secuencia'),
        opcional=True,
        columnas=(
        Columna("NRO_CONTRATO", "nro_contrato", "varchar(14)"),
        Columna("SECUENCIA", "secuencia", "bigint"),
        Columna("NUMERO_PROCEDIMIENTO", None),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("CEDULA_INSTITUCION", "cedula_institucion", "cedula(20)"),
        Columna("TIPO_CONTRATO", "tipo_contrato", "varchar(120)"),
        Columna("TIPO_MODIFICACION", "tipo_modificacion", "varchar(120)"),
        Columna("FECHA_NOTIFICACION", "fecha_notificacion", "timestamp"),
        Columna("FECHA_ELABORACION", "fecha_elaboracion", "timestamp"),
        Columna("TIPO_AUTORIZACION", "tipo_autorizacion", "varchar(120)"),
        Columna("TIPO_DISMINUCION", "tipo_disminucion", "varchar(120)"),
        Columna("VIGENCIA", "vigencia", "varchar(120)"),
        Columna("MONEDA", "moneda", "varchar(120)"),
        Columna("FECHA_INI_SUSP", "fecha_ini_susp", "timestamp"),
        Columna("FECHA_REINI_CONT", "fecha_reini_cont", "timestamp"),
        Columna("PLAZO_SUSP", "plazo_susp", "numeric(20,6)"),
        Columna("FECHA_MODIFICACION", "fecha_modificacion", "timestamp"),
        Columna("FECHA_INI_PRORR", "fecha_ini_prorr", "timestamp"),
        Columna("FECHA_FIN_PRORR", "fecha_fin_prorr", "timestamp"),
        Columna("NRO_CONTRATO_WEB", "nro_contrato_web", "varchar(14)"),
        ),
        enriquece=(
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento", "CEDULA_INSTITUCION": "ced_institucion"}),
        ),
        indices=(('nro_sicop',), ('cedula_institucion',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="DetalleCarteles.csv",
        tabla="detalle_carteles",
        clave=('nro_sicop',),
        opcional=True,
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("CEDULA_INSTITUCION", "cedula_institucion", "cedula(20)"),
        Columna("FECHA_PUBLICACION", "fecha_publicacion", "timestamp"),
        Columna("NRO_PROCEDIMIENTO", None),
        Columna("TIPO_PROCEDIMIENTO", "tipo_procedimiento", "varchar(120)"),
        Columna("MODALIDAD_PROCEDIMIENTO", "modalidad_procedimiento", "varchar(120)"),
        Columna("CARTEL_STAT", "cartel_stat", "varchar(120)"),
        Columna("CARTEL_NM", "cartel_nm", "varchar(14)"),
        Columna("FECHAH_APERTURA", "fechah_apertura", "timestamp"),
        Columna("CODIGO_BPIP", "codigo_bpip", "varchar(14)"),
        Columna("CLAS_OBJ", "clas_obj", "varchar(14)"),
        Columna("COD_EXCEPCION", "cod_excepcion", "varchar(14)"),
        Columna("DES_EXCEPCION", "des_excepcion", "varchar(120)"),
        Columna("MONTO_EST", "monto_est", "numeric(20,6)"),
        Columna("FECHA_MOD", "fecha_mod", "timestamp"),
        ),
        enriquece=(
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NRO_PROCEDIMIENTO": "numero_procedimiento", "CEDULA_INSTITUCION": "ced_institucion"}),
        ),
        indices=(('nro_sicop',), ('cedula_institucion',)),
    ),
    TablaSpec(
        archivo="DetalleLineaCartel.csv",
        tabla="detalle_linea_cartel",
        clave=('nro_sicop', 'numero_linea', 'numero_partida'),
        opcional=True,
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NUMERO_LINEA", "numero_linea", "bigint"),
        Columna("NUMERO_PARTIDA", "numero_partida", "bigint"),
        Columna("CANTIDAD_SOLICITADA", "cantidad_solicitada", "numeric(20,6)"),
        Columna("PRECIO_UNITARIO_ESTIMADO", "precio_unitario_estimado", "numeric(20,6)"),
        Columna("TIPO_MONEDA", "tipo_moneda", "varchar(120)"),
        Columna("TIPO_CAMBIO_CRC", "tipo_cambio_crc", "numeric(20,6)"),
        Columna("TIPO_CAMBIO_DOLAR", "tipo_cambio_dolar", "numeric(20,6)"),
        Columna("CODIGO_IDENTIFICACION", "codigo_identificacion", "varchar(14)"),
        Columna("MONTO_RESERVADO", "monto_reservado", "numeric(20,6)"),
        Columna("DESC_LINEA", "desc_linea", "varchar(120)"),
        ),
        indices=(('nro_sicop',),),
    ),
    TablaSpec(
        archivo="FechaPorEtapas.csv",
        tabla="fecha_por_etapas",
        clave=('nro_sicop', 'linea'),
        opcional=True,
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NUMERO_PROCEDIMIENTO", None),
        Columna("CARTEL_SEQ", "cartel_seq", "bigint"),
        Columna("PARTIDA", "partida", "bigint"),
        Columna("LINEA", "linea", "bigint"),
        Columna("PUBLICACION", "publicacion", "varchar(120)"),
        Columna("FECHA_APERTURA", "fecha_apertura", "timestamp"),
        Columna("SOLICITUD_ESTUDIOS_TECNICOS", "solicitud_estudios_tecnicos", "varchar(120)"),
        Columna("COMUNICACION", "comunicacion", "varchar(120)"),
        Columna("SOLICITUD_PAGO_ESP_FISCALES", "solicitud_pago_esp_fiscales", "varchar(120)"),
        Columna("RESPUESTA_ESTUDIOS_TECNICOS", "respuesta_estudios_tecnicos", "varchar(120)"),
        Columna("SOLICITUD_RECOM_ADJUD", "solicitud_recom_adjud", "varchar(120)"),
        Columna("RESPUESTA_RECOM_ADJUD", "respuesta_recom_adjud", "varchar(120)"),
        Columna("SOLICITUD_ADJUD", "solicitud_adjud", "varchar(120)"),
        Columna("RESPUESTA_ADJUD", "respuesta_adjud", "varchar(120)"),
        Columna("ADJUDICACION_FIRME", "adjudicacion_firme", "varchar(120)"),
        Columna("FECHA_RESUL_PAGO_ESP_FISCALES", "fecha_resul_pago_esp_fiscales", "timestamp"),
        Columna("FECHA_ELABORACION_CONTRATO", "fecha_elaboracion_contrato", "timestamp"),
        Columna("SOLICITUD_APROBACION_CONTRATO", "solicitud_aprobacion_contrato", "varchar(120)"),
        Columna("RESPUESTA_APROBACION_CONTRATO", "respuesta_aprobacion_contrato", "varchar(120)"),
        Columna("FECHA_NOTIFICACION", "fecha_notificacion", "timestamp"),
        Columna("FECHA_1RA_SOL_RECEPCION", "fecha_1ra_sol_recepcion", "timestamp"),
        Columna("FECHA_1RA_SOL_RECEP_PROVI", "fecha_1ra_sol_recep_provi", "timestamp"),
        Columna("FECHA_ULT_SOL_RECEP_DEFI", "fecha_ult_sol_recep_defi", "timestamp"),
        Columna("FECHA_1RA_SOL_PAGO", "fecha_1ra_sol_pago", "timestamp"),
        Columna("FECHA_ULT_SOL_PAGO", "fecha_ult_sol_pago", "timestamp"),
        Columna("FECHA_RESUL_PAGO", "fecha_resul_pago", "timestamp"),
        ),
        enriquece=(
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento"}),
        ),
        indices=(('nro_sicop',),),
    ),
    TablaSpec(
        archivo="FuncionariosInhibicion.csv",
        tabla="funcionarios_inhibicion",
        clave=('ced_institucion', 'ced_funcionario'),
        columnas=(
        Columna("CED_INSTITUCION", "ced_institucion", "cedula(20)"),
        Columna("CED_FUNCIONARIO", "ced_funcionario", "cedula(20)"),
        Columna("NOM_FUNCIONARIO", "nom_funcionario", "varchar(70)"),
        Columna("FECHA_INICIO", "fecha_inicio", "date"),
        Columna("FECHA_FIN", "fecha_fin", "date"),
        Columna("ESTADO", "estado", "varchar(15)"),
        Columna("fecha_registro", "fecha_registro", "date"),
        ),
        indices=(('ced_institucion',),),
    ),
    TablaSpec(
        archivo="Garantias.csv",
        tabla="garantias",
        clave=('nro_garantia',),
        opcional=True,
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NUMERO_PROCEDIMIENTO", None),
        Columna("DESCRIPCION_PROCEDIMIENTO", None),
        Columna("TIPO_PROCEDIMIENTO", "tipo_procedimiento", "varchar(120)"),
        Columna("NOMBRE_INSTITUCION", None),
        Columna("CEDULA_INSTITUCION", "cedula_institucion", "cedula(20)"),
        Columna("NOMBRE_PROVEEDOR", None),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("TIPO_GARANTIA", "tipo_garantia", "varchar(120)"),
        Columna("MONTO", "monto", "numeric(20,6)"),
        Columna("ESTADO", "estado", "varchar(120)"),
        Columna("VIGENCIA", "vigencia", "varchar(120)"),
        Columna("fecha_registro", "fecha_registro", "timestamp"),
        Columna("nro_garantia", "nro_garantia", "varchar(14)"),
        Columna("ced_garante", "ced_garante", "cedula(20)"),
        Columna("gara_seq", "gara_seq", "bigint"),
        Columna("garantia_NM", "garantia_nm", "varchar(14)"),
        ),
        enriquece=(
        Enriquecimiento("dim_institucion", "CEDULA_INSTITUCION", {"NOMBRE_INSTITUCION": "nombre"}),
        Enriquecimiento("dim_proveedor", "CEDULA_PROVEEDOR", {"NOMBRE_PROVEEDOR": "nombre"}),
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento", "DESCRIPCION_PROCEDIMIENTO": "descripcion", "CEDULA_INSTITUCION": "ced_institucion"}),
        ),
        indices=(('nro_sicop',), ('cedula_institucion',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="InstitucionesRegistradas.csv",
        tabla="dim_institucion",
        clave=('cedula',),
        particionada=False,
        columna_libre="NOMBRE_INSTITUCION",
        columnas=(
        Columna("CEDULA", "cedula", "cedula(20)"),
        Columna("NOMBRE_INSTITUCION", "nombre", "varchar(236)"),
        Columna("ZONA_GEO_INST", "zona_geo", "varchar(69)"),
        Columna("FECHA_INGRESO", "fecha_ingreso", "date"),
        Columna("FECHA_MOD", "fecha_mod", "date"),
        ),
    ),
    TablaSpec(
        archivo="InvitacionProcedimiento.csv",
        tabla="invitacion_procedimiento",
        clave=('nro_sicop', 'cedula_proveedor'),
        columna_libre="NOMBRE_PROVEEDOR",
        columnas=(
        Columna("SECUENCIA", "secuencia", "bigint"),
        Columna("CED_INSTITUCION", "ced_institucion", "cedula(20)"),
        Columna("INSTITUCION", None),
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("NOMBRE_PROVEEDOR", None),
        Columna("NUMERO_PROCEDIMIENTO", None),
        Columna("FECHA_INVITACION", "fecha_invitacion", "timestamp"),
        ),
        enriquece=(
        Enriquecimiento("dim_institucion", "CED_INSTITUCION", {"INSTITUCION": "nombre"}),
        Enriquecimiento("dim_proveedor", "CEDULA_PROVEEDOR", {"NOMBRE_PROVEEDOR": "nombre"}),
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento", "CED_INSTITUCION": "ced_institucion"}),
        ),
        indices=(('nro_sicop',),),
    ),
    TablaSpec(
        archivo="LineasAdjudicadas.csv",
        tabla="lineas_adjudicadas",
        clave=('nro_sicop', 'nro_oferta', 'nro_linea'),
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NRO_OFERTA", "nro_oferta", "varchar(39)"),
        Columna("CODIGO_PRODUCTO", "codigo_producto", "varchar(30)"),
        Columna("NRO_LINEA", "nro_linea", "bigint"),
        Columna("NRO_ACTO", "nro_acto", "bigint"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("CANTIDAD_ADJUDICADA", "cantidad_adjudicada", "numeric(20,6)"),
        Columna("PRECIO_UNITARIO_ADJUDICADO", "precio_unitario_adjudicado", "numeric(20,6)"),
        Columna("TIPO_MONEDA", "tipo_moneda", "varchar(11)"),
        Columna("DESCUENTO", "descuento", "numeric(20,6)"),
        Columna("IVA", "iva", "numeric(20,6)"),
        Columna("OTROS_IMPUESTOS", "otros_impuestos", "numeric(20,6)"),
        Columna("ACARREOS", "acarreos", "numeric(20,6)"),
        Columna("TIPO_CAMBIO_CRC", "tipo_cambio_crc", "numeric(20,6)"),
        Columna("TIPO_CAMBIO_DOLAR", "tipo_cambio_dolar", "numeric(20,6)"),
        ),
        indices=(('nro_sicop',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="LineasContratadas.csv",
        tabla="lineas_contratadas",
        clave=('nro_sicop', 'nro_contrato', 'nro_linea_contrato'),
        columna_libre="DESC_PRODUCTO",
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NRO_LINEA_CONTRATO", "nro_linea_contrato", "bigint"),
        Columna("NRO_LINEA_CARTEL", "nro_linea_cartel", "bigint"),
        Columna("NRO_CONTRATO", "nro_contrato", "varchar(20)"),
        Columna("SECUENCIA", "secuencia", "bigint"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("CODIGO_PRODUCTO", "codigo_producto", "varchar(30)"),
        Columna("CANTIDAD_CONTRATADA", "cantidad_contratada", "numeric(20,6)"),
        Columna("PRECIO_UNITARIO", "precio_unitario", "numeric(20,6)"),
        Columna("TIPO_MONEDA", "tipo_moneda", "varchar(11)"),
        Columna("DESCUENTO", "descuento", "numeric(20,6)"),
        Columna("IVA", "iva", "numeric(20,6)"),
        Columna("OTROS_IMPUESTOS", "otros_impuestos", "numeric(20,6)"),
        Columna("ACARREOS", "acarreos", "numeric(20,6)"),
        Columna("TIPO_CAMBIO_CRC", "tipo_cambio_crc", "numeric(20,6)"),
        Columna("TIPO_CAMBIO_DOLAR", "tipo_cambio_dolar", "numeric(20,6)"),
        Columna("NRO_ACTO", "nro_acto", "bigint"),
        Columna("DESC_PRODUCTO", "desc_producto", "text"),
        Columna("cantidad_aumentada", "cantidad_aumentada", "numeric(20,6)"),
        Columna("cantidad_disminuida", "cantidad_disminuida", "numeric(20,6)"),
        Columna("monto_aumentado", "monto_aumentado", "numeric(20,6)"),
        Columna("monto_disminuido", "monto_disminuido", "numeric(20,6)"),
        ),
        indices=(('nro_sicop',), ('cedula_proveedor',), ('nro_contrato',)),
    ),
    TablaSpec(
        archivo="LineasOfertadas.csv",
        tabla="lineas_ofertadas",
        clave=('nro_sicop', 'nro_oferta', 'nro_linea'),
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NRO_OFERTA", "nro_oferta", "varchar(39)"),
        Columna("NRO_LINEA", "nro_linea", "bigint"),
        Columna("CODIGO_PRODUCTO", "codigo_producto", "varchar(30)"),
        Columna("CANTIDAD_OFERTADA", "cantidad_ofertada", "numeric(20,6)"),
        Columna("PRECIO_UNITARIO_OFERTADO", "precio_unitario_ofertado", "numeric(20,6)"),
        Columna("TIPO_MONEDA", "tipo_moneda", "varchar(11)"),
        Columna("DESCUENTO", "descuento", "numeric(20,6)"),
        Columna("IVA", "iva", "numeric(20,6)"),
        Columna("OTROS_IMPUESTOS", "otros_impuestos", "numeric(20,6)"),
        Columna("ACARREOS", "acarreos", "numeric(20,6)"),
        Columna("TIPO_CAMBIO_CRC", "tipo_cambio_crc", "numeric(20,6)"),
        Columna("TIPO_CAMBIO_DOLAR", "tipo_cambio_dolar", "numeric(20,6)"),
        Columna("CODIGO_PRODUCTO_CL", "codigo_producto_cl", "varchar(22)"),
        ),
        indices=(('nro_sicop',),),
    ),
    TablaSpec(
        archivo="LineasRecibidas.csv",
        tabla="lineas_recibidas",
        clave=('nro_sicop', 'nro_linea'),
        columna_libre="desc_producto",
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NRO_CONTRATO", "nro_contrato", "varchar(20)"),
        Columna("SECUENCIA", "secuencia", "bigint"),
        Columna("NRO_RECEP_PROVISIONAL", "nro_recep_provisional", "varchar(25)"),
        Columna("ESTADO_RECEP_PROVISIONAL", "estado_recep_provisional", "varchar(36)"),
        Columna("NRO_RECEP_DEFINITIVA", "nro_recep_definitiva", "varchar(25)"),
        Columna("ESTADO_RECEP_DEFINITIVA", "estado_recep_definitiva", "varchar(48)"),
        Columna("NRO_LINEA", "nro_linea", "bigint"),
        Columna("ENTREGA", "entrega", "bigint"),
        Columna("CODIGO_PRODUCTO", "codigo_producto", "varchar(30)"),
        Columna("CANTIDAD_REAL_RECIBIDA", "cantidad_real_recibida", "numeric(20,6)"),
        Columna("desc_producto", "desc_producto", "text"),
        Columna("precio", "precio", "numeric(20,6)"),
        Columna("dias_adelanto_atraso", "dias_adelanto_atraso", "bigint"),
        Columna("fecha_recepcion_Definitiva", "fecha_recepcion_definitiva", "varchar(43)"),
        ),
        indices=(('nro_sicop',), ('nro_contrato',)),
    ),
    TablaSpec(
        archivo="Ofertas.csv",
        tabla="ofertas",
        clave=('nro_sicop', 'nro_oferta'),
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NRO_OFERTA", "nro_oferta", "varchar(39)"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("FECHA_PRESENTA_OFERTA", "fecha_presenta_oferta", "date"),
        Columna("TIPO_OFERTA", "tipo_oferta", "varchar(31)"),
        Columna("ID_CONSORCIO", "id_consorcio", "varchar(16)"),
        ),
        indices=(('nro_sicop',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="OrdenPedido.csv",
        tabla="orden_pedido",
        clave=('nro_orden', 'linea_ord_pedido'),
        columna_libre="DESC_PROCEDIMIENTO",
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NUMERO_PROCEDIMIENTO", None),
        Columna("NRO_CONTRATO", "nro_contrato", "varchar(22)"),
        Columna("CONTRACT_NO", "contract_no", "varchar(20)"),
        Columna("SECUENCIA_CONTRATO", "secuencia_contrato", "bigint"),
        Columna("TOTAL_ORDEN", "total_orden", "numeric(20,6)"),
        Columna("TOTALESTIMADO", "totalestimado", "numeric(20,6)"),
        Columna("ESTADO_ORDEN", "estado_orden", "varchar(65)"),
        Columna("DESC_PROCEDIMIENTO", None),
        Columna("CEDULAPROVEEDOR", "cedulaproveedor", "cedula(20)"),
        Columna("NOMBRE_PROVEEDOR", None),
        Columna("FECHAREGISTRO", "fecharegistro", "timestamp"),
        Columna("FECHA_PROV_RECIBE_ORDEN", "fecha_prov_recibe_orden", "timestamp"),
        Columna("USD_MONT", "usd_mont", "numeric(20,6)"),
        Columna("NRO_ORDEN", "nro_orden", "varchar(22)"),
        Columna("MONEDA_ORDEN", "moneda_orden", "varchar(11)"),
        Columna("FECHA_NOTIFICACION_ORDEN", "fecha_notificacion_orden", "timestamp"),
        Columna("FECHA_ELABORACION_ORDEN", "fecha_elaboracion_orden", "timestamp"),
        Columna("FECHA_PROVEEDOR_RECIBE_ORDEN", "fecha_proveedor_recibe_orden", "timestamp"),
        Columna("LINEA_ORD_PEDIDO", "linea_ord_pedido", "bigint"),
        Columna("FECHA_REC_PEDIDO", "fecha_rec_pedido", "timestamp"),
        Columna("SECUENCIA", "secuencia", "bigint"),
        ),
        enriquece=(
        Enriquecimiento("dim_proveedor", "CEDULAPROVEEDOR", {"NOMBRE_PROVEEDOR": "nombre"}),
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento", "DESC_PROCEDIMIENTO": "descripcion"}),
        ),
        indices=(('nro_sicop',), ('cedulaproveedor',), ('nro_contrato',)),
    ),
    TablaSpec(
        archivo="ProcedimientoADM.csv",
        tabla="procedimiento_a_d_m",
        clave=('nro_sicop', 'numero_pa'),
        opcional=True,
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NUMERO_PROCEDIMIENTO", None),
        Columna("NOMBRE_PROVEEDOR", None),
        Columna("NUMERO_PA", "numero_pa", "varchar(14)"),
        Columna("NOMBRE_INSTITUCION", None),
        Columna("CEDULA_INSTITUCION", "cedula_institucion", "cedula(20)"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("FECHA_NOTIFICACION", "fecha_notificacion", "timestamp"),
        Columna("INHAB_APERC", "inhab_aperc", "boolean"),
        Columna("MULTA_CAUSULA", "multa_causula", "boolean"),
        ),
        enriquece=(
        Enriquecimiento("dim_institucion", "CEDULA_INSTITUCION", {"NOMBRE_INSTITUCION": "nombre"}),
        Enriquecimiento("dim_proveedor", "CEDULA_PROVEEDOR", {"NOMBRE_PROVEEDOR": "nombre"}),
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento", "CEDULA_INSTITUCION": "ced_institucion"}),
        ),
        indices=(('nro_sicop',), ('cedula_institucion',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="ProcedimientoAdjudicacion.csv",
        tabla="procedimiento_adjudicacion",
        clave=('nro_sicop', 'linea'),
        columna_libre="DESCR_BIEN_SERVICIO",
        columnas=(
        Columna("CEDULA", "cedula", "cedula(20)"),
        Columna("INSTITUCION", None),
        Columna("ANO", "ano", "varchar(14)"),
        Columna("NUMERO_PROCEDIMIENTO", "numero_procedimiento", "varchar(30)"),
        Columna("DESCR_PROCEDIMIENTO", None),
        Columna("LINEA", "linea", "bigint"),
        Columna("PROD_ID", "prod_id", "varchar(22)"),
        Columna("DESCR_BIEN_SERVICIO", "descr_bien_servicio", "text"),
        Columna("CANTIDAD", "cantidad", "numeric(20,6)"),
        Columna("UNIDAD_MEDIDA", "unidad_medida", "varchar(11)"),
        Columna("MONTO_UNITARIO", "monto_unitario", "numeric(20,6)"),
        Columna("MONEDA_PRECIO_EST", "moneda_precio_est", "numeric(20,6)"),
        Columna("MONEDA_ADJUDICADA", "moneda_adjudicada", "varchar(11)"),
        Columna("MONTO_ADJU_LINEA", "monto_adju_linea", "numeric(20,6)"),
        Columna("MONTO_ADJU_LINEA_CRC", "monto_adju_linea_crc", "numeric(20,6)"),
        Columna("MONTO_ADJU_LINEA_USD", "monto_adju_linea_usd", "numeric(20,6)"),
        Columna("FECHA_ADJUD_FIRME", "fecha_adjud_firme", "date"),
        Columna("FECHA_SOL_CONTRA", "fecha_sol_contra", "date"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("NOMBRE_PROVEEDOR", None),
        Columna("PERFIL_PROV", "perfil_prov", "varchar(56)"),
        Columna("CEDULA_REPRESENTANTE", "cedula_representante", "cedula(20)"),
        Columna("REPRESENTANTE", "representante", "varchar(53)"),
        Columna("OBJETO_GASTO", "objeto_gasto", "varchar(14)"),
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("TIPO_PROCEDIMIENTO", "tipo_procedimiento", "varchar(43)"),
        Columna("MODALIDAD_PROCEDIMIENTO", "modalidad_procedimiento", "varchar(45)"),
        Columna("fecha_rev", "fecha_rev", "timestamp"),
        Columna("FECHA_SOL_CONTRA_CL", "fecha_sol_contra_cl", "date"),
        Columna("PROD_ID_CL", "prod_id_cl", "varchar(22)"),
        ),
        enriquece=(
        Enriquecimiento("dim_institucion", "CEDULA", {"INSTITUCION": "nombre"}),
        Enriquecimiento("dim_proveedor", "CEDULA_PROVEEDOR", {"NOMBRE_PROVEEDOR": "nombre"}),
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento", "DESCR_PROCEDIMIENTO": "descripcion", "CEDULA": "ced_institucion"}),
        ),
        indices=(('nro_sicop',), ('cedula',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="Proveedores.csv",
        tabla="dim_proveedor",
        clave=('cedula_proveedor',),
        particionada=False,
        columna_libre="NOMBRE_PROVEEDOR",
        columnas=(
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("NOMBRE_PROVEEDOR", "nombre", "varchar(249)"),
        Columna("TIPO_PROVEEDOR", "tipo_proveedor", "varchar(32)"),
        Columna("TAMAÑO_PROVEEDOR", "tamano_proveedor", "varchar(28)"),
        Columna("FECHA_CONSTITUCION", "fecha_constitucion", "fecha_compacta"),
        Columna("FECHA_EXPIRACION", "fecha_expiracion", "fecha_compacta"),
        Columna("zona_geo_prov", "zona_geo", "varchar(75)"),
        Columna("fecha_registro", "fecha_registro", "date"),
        Columna("fecha_mod", "fecha_mod", "date"),
        ),
    ),
    TablaSpec(
        archivo="ReajustePrecios.csv",
        tabla="reajuste_precios",
        clave=('nro_contrato', 'numero_reajuste'),
        dedup=True,
        columna_libre="DES_PRODUCTO",
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NUMERO_PROCEDIMIENTO", None),
        Columna("NOMBRE_INSTITUCION", None),
        Columna("CEDULA_INSTITUCION", "cedula_institucion", "cedula(20)"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("NOMBRE_PROVEEDOR", None),
        Columna("FECHA_ELABORACION", "fecha_elaboracion", "timestamp"),
        Columna("CODIGO_PRODUCTO", "codigo_producto", "varchar(30)"),
        Columna("DES_PRODUCTO", "des_producto", "text"),
        Columna("NRO_CONTRATO", "nro_contrato", "varchar(20)"),
        Columna("NRO_LINEA_CONTRATO", "nro_linea_contrato", "bigint"),
        Columna("CANTIDAD_CONTRATADA", "cantidad_contratada", "numeric(20,6)"),
        Columna("PRECIO_UNITARIO", "precio_unitario", "numeric(20,6)"),
        Columna("NUMERO_REAJUSTE", "numero_reajuste", "varchar(14)"),
        Columna("PRECIO_ANT_ULT_RJ", "precio_ant_ult_rj", "numeric(20,6)"),
        Columna("MONTO_REAJUSTE", "monto_reajuste", "numeric(20,6)"),
        Columna("NUEVO_PRECIO", "nuevo_precio", "numeric(20,6)"),
        Columna("PORC_INCR_ULT_RJ", "porc_incr_ult_rj", "numeric(20,6)"),
        Columna("FECHA_INICIO", "fecha_inicio", "date"),
        Columna("FECHA_FIN", "fecha_fin", "date"),
        Columna("MESES_APP", "meses_app", "bigint"),
        Columna("DIAS_APP", "dias_app", "bigint"),
        Columna("TIPO_MONEDA", "tipo_moneda", "varchar(11)"),
        Columna("MONTO_TOTAL", "monto_total", "numeric(20,6)"),
        ),
        enriquece=(
        Enriquecimiento("dim_institucion", "CEDULA_INSTITUCION", {"NOMBRE_INSTITUCION": "nombre"}),
        Enriquecimiento("dim_proveedor", "CEDULA_PROVEEDOR", {"NOMBRE_PROVEEDOR": "nombre"}),
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento", "CEDULA_INSTITUCION": "ced_institucion"}),
        ),
        indices=(('nro_sicop',), ('cedula_institucion',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="Recepciones.csv",
        tabla="recepciones",
        clave=('nro_sicop', 'nro_recep_definitiva'),
        columna_libre="nombre_proveedor",
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NRO_CONTRATO", "nro_contrato", "varchar(20)"),
        Columna("NRO_RECEP_DEFINITIVA", "nro_recep_definitiva", "varchar(25)"),
        Columna("FECHA_RECEP_DEFINITIVA", "fecha_recep_definitiva", "date"),
        Columna("nro_procedimiento", None),
        Columna("cedula_proveedor", "cedula_proveedor", "cedula(20)"),
        Columna("cedula_institucion", "cedula_institucion", "cedula(20)"),
        Columna("moneda", "moneda", "varchar(11)"),
        Columna("nombre_proveedor", None),
        Columna("fecha_ent_ini", "fecha_ent_ini", "date"),
        ),
        enriquece=(
        Enriquecimiento("dim_proveedor", "cedula_proveedor", {"nombre_proveedor": "nombre"}),
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"nro_procedimiento": "numero_procedimiento", "cedula_institucion": "ced_institucion"}),
        ),
        indices=(('nro_sicop',), ('cedula_institucion',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="RecursosObjecion.csv",
        tabla="recursos_objecion",
        clave=('nro_recurso',),
        columna_libre="desc_procedimiento",
        columnas=(
        Columna("NRO_RECURSO", "nro_recurso", "varchar(14)"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NRO_ACTO", "nro_acto", "bigint"),
        Columna("LINEA_OBJETADA", "linea_objetada", "bigint"),
        Columna("TIPO_RECURSO", "tipo_recurso", "varchar(22)"),
        Columna("RESULTADO", "resultado", "varchar(36)"),
        Columna("CAUSA_RESULTADO", "causa_resultado", "varchar(52)"),
        Columna("FECHA_PRESENTACION_RECURSO", "fecha_presentacion_recurso", "timestamp"),
        Columna("nro_procedimiento", None),
        Columna("desc_procedimiento", None),
        Columna("reqer_nm", "reqer_nm", "varchar(51)"),
        Columna("recurso_stat", "recurso_stat", "varchar(18)"),
        ),
        enriquece=(
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"nro_procedimiento": "numero_procedimiento", "desc_procedimiento": "descripcion"}),
        ),
        indices=(('nro_sicop',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="Remates.csv",
        tabla="remates",
        clave=('nro_sicop', 'ced_proveedor'),
        dedup=True,
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NUMERO_PROCEDIMIENTO", None),
        Columna("FECHA_INVITACION", "fecha_invitacion", "timestamp"),
        Columna("CED_PROVEEDOR", "ced_proveedor", "cedula(20)"),
        Columna("MONTO_PUJA", "monto_puja", "numeric(20,6)"),
        Columna("MONEDA_PUJA", "moneda_puja", "varchar(11)"),
        Columna("MONTO_EST_LINEA", "monto_est_linea", "numeric(20,6)"),
        Columna("CANT_EST", "cant_est", "numeric(20,6)"),
        Columna("MONEDA_ADJ", "moneda_adj", "varchar(11)"),
        Columna("MONTO_ADJ", "monto_adj", "numeric(20,6)"),
        Columna("CANT_ADJ", "cant_adj", "bigint"),
        Columna("TIPO_CAMBIO_MONEDA", "tipo_cambio_moneda", "numeric(20,6)"),
        Columna("fecha_mod", "fecha_mod", "date"),
        ),
        enriquece=(
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NUMERO_PROCEDIMIENTO": "numero_procedimiento"}),
        ),
        indices=(('nro_sicop',), ('ced_proveedor',)),
    ),
    TablaSpec(
        archivo="SancionProveedores.csv",
        tabla="sancion_proveedores",
        clave=('cedula_proveedor', 'no_resolucion'),
        delimitador=",",
        columna_libre="DESCR_SANCION",
        columnas=(
        Columna("NOMBRE_INSTITUCION", None),
        Columna("CEDULA_INSTITUCION", "cedula_institucion", "cedula(20)"),
        Columna("CODIGO_PRODUCTO", "codigo_producto", "varchar(22)"),
        Columna("DESCRIP_PRODUCTO", "descrip_producto", "varchar(96)"),
        Columna("CEDULA_PROVEEDOR", "cedula_proveedor", "cedula(20)"),
        Columna("NOMBRE_PROVEEDOR", None),
        Columna("TIPO_SANCION", "tipo_sancion", "varchar(26)"),
        Columna("DESCR_SANCION", "descr_sancion", "text"),
        Columna("INICIO_SANCION", "inicio_sancion", "fecha_compacta"),
        Columna("FINAL_SANCION", "final_sancion", "fecha_compacta"),
        Columna("ESTADO", "estado", "varchar(9)"),
        Columna("NO_RESOLUCION", "no_resolucion", "varchar(22)"),
        Columna("fecha_registro", "fecha_registro", "date"),
        ),
        enriquece=(
        Enriquecimiento("dim_institucion", "CEDULA_INSTITUCION", {"NOMBRE_INSTITUCION": "nombre"}),
        Enriquecimiento("dim_proveedor", "CEDULA_PROVEEDOR", {"NOMBRE_PROVEEDOR": "nombre"}),
        ),
        indices=(('cedula_institucion',), ('cedula_proveedor',)),
    ),
    TablaSpec(
        archivo="SistemaEvaluacionOfertas.csv",
        tabla="sistema_evaluacion_ofertas",
        clave=('nro_sicop', 'eval_item_seqno'),
        dedup=True,
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("EVAL_ITEM_SEQNO", "eval_item_seqno", "bigint"),
        Columna("FACTOR_EVAL", "factor_eval", "text"),
        Columna("PORC_EVAL", "porc_eval", "numeric(20,6)"),
        Columna("fecha_registro", "fecha_registro", "date"),
        ),
        indices=(('nro_sicop',),),
    ),
    TablaSpec(
        archivo="Sistemas.csv",
        tabla="sistemas",
        clave=('nro_sicop', 'numero_linea'),
        opcional=True,
        columnas=(
        Columna("NRO_SICOP", "nro_sicop", "varchar(20)"),
        Columna("NUMERO_LINEA", "numero_linea", "bigint"),
        Columna("NUMERO_PARTIDA", "numero_partida", "bigint"),
        Columna("DESC_LINEA", "desc_linea", "varchar(120)"),
        Columna("CEDULA_INSTITUCION", "cedula_institucion", "cedula(20)"),
        Columna("NRO_PROCEDIMIENTO", None),
        Columna("TIPO_PROCEDIMIENTO", "tipo_procedimiento", "varchar(120)"),
        Columna("FECHA_PUBLICACION", "fecha_publicacion", "timestamp"),
        ),
        enriquece=(
        Enriquecimiento("dim_procedimiento", "NRO_SICOP", {"NRO_PROCEDIMIENTO": "numero_procedimiento", "CEDULA_INSTITUCION": "ced_institucion"}),
        ),
        indices=(('nro_sicop',), ('cedula_institucion',)),
    ),
)

validar_specs(list(TABLAS))

POR_ARCHIVO = {t.archivo: t for t in TABLAS}
POR_TABLA = {t.tabla: t for t in TABLAS}
HECHOS = tuple(t for t in TABLAS if t.particionada)
DIMENSIONES = tuple(t for t in TABLAS if not t.particionada)
